# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weathermail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.RemoveField(
            model_name='location',
            name='rank',
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('city', 'state')]),
        ),
    ]
